### ISSUE TITLE
[error] FE 프로젝트 생성 실행 실패

### ISSUE THREAD

**Issue by do02reen24** [boostcamp-2020/IssueTracker-08#138]
| Name       | about                              | title | labels | assignees |
| ---------- | ---------------------------------- | ----- | ------ | --------- |
| Bug report | Create a report to help us improve |       |        |           |

<br/>

### 🤔 Current behaviour (bug)
```bash
$ npm run dev

> client@1.0.0 dev C:\Users\dykim\Desktop\FE\IssueTracker-08\Client
> webpack-dev-server --progress --mode development

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- C:\Users\dykim\Desktop\FE\IssueTracker-08\Client\node_modules\webpack-dev-server\bin\webpack-dev-server.js    
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\dykim\Desktop\FE\IssueTracker-08\Client\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\dykim\\Desktop\\FE\\IssueTracker-08\\Client\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@1.0.0 dev: `webpack-dev-server --progress --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dykim\AppData\Roaming\npm-cache\_logs\2020-11-02T06_50_55_874Z-debug.log
```

<br/>

### 😮 Expected behaviour (correct)

Write here

<br/>

### 😣 버그 재현방법

1. Write here
2. Write here

**Comment by yoonwoo123** [comment]
webpack과 webpack-dev-server 버전이 서로간 충돌로 인해서 발생하는 에러로
[참조](https://aspdotnet.tistory.com/2192) 를 보고 시도해보았으나
옛날 버전이라서 mode를 찾을 수 없다는 다른 에러가 발생하였다.

**Comment by do02reen24** [comment]
```js
    "css-loader": "^4.3.0",
    "style-loader": "^1.2.1",
    "webpack": "^4.44.2",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
```
위와 같이 package.json의 설정을 변경하여 실행 오류 문제를 해결할 수 있었다.
버전간 지원충돌로 인해 발생한 문제였다.

**Comment by Yejikwon** [comment]
버전관련해서 참고했던 블로그는 '김정환님 블로그'를 참고했습니다!
